# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_result_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='created_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='sentiment',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweet_text',
            field=models.TextField(max_length=250),
        ),
    ]
